import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          EduGamze
        </h1>

        <p className={styles.description}>
          Choose a Game to Play and Learn         
        </p>

        <div className={styles.grid}>
          <a href="/spellinggame" className={styles.card}>
            <h2>Spelling &rarr;</h2>
            <p>Simply listen to the pronounciation and guess</p>
          </a>

          <a href="/mapgame" className={styles.card}>
            <h2>Maps &rarr;</h2>
            <p>Just enter the name of the highlighted country</p>
          </a>

          <a
            href="/flaggame"
            className={styles.card}
          >
            <h2>Flags &rarr;</h2>
            <p>Guess by looking at a flag image and some hints</p>
          </a>

          <a
            href="/"
            className={styles.card}
          >
            <h2>History &rarr;</h2>
            <p>
             Coming soon...
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
